---
title: "Application Exercise 2: Poisson"
author: "Your name here"
date: "Today's date here"
format: html
---

::: callout-important

This Application Exercise is due on Friday, September 11 at 11:59pm. To be considered on time, the following must be done by the due date:

- Final `.pdf` file submitted on Canvas

- While late work is accepted for HW and Labs, no late work is accepted for AEs. 

:::

## Getting started

Download the template for today's Application Exercise (AE) from Canvas. Open the file, and type your name and today's date in the YAML. Save your file as `ae-02.qmd` in your project folder. 

Render your document to ensure the formatting all looks good. 



## Hospital Visits: Poisson Example

Suppose that in a hospital emergency department, the average number of asthma-related visits per hour is 3. Let $Y$ be the number of asthma visits in one hour. Then $Y \sim Poisson(\lambda=3)$

### Exercise 1

What is the probability that in a given hour, exactly 5 asthma patients arrive? Use the `dpois` function to compute your answer and provide a 1-sentence conclusion.

```{r}
# type code here
```

[type response here]

## Submission

As you’ve seen previously, we can **Render** the template into an .html file that can be opened by any web browser. To export it as a .pdf, open the file in your web browser and then print to or save as a .pdf document. Your TAs will show you how if you need help! (There is a way to directly knit to a .pdf file, but it’s quite a bit more involved.)

You will submit the PDF documents for Application Exercises directly to Canvas.

To submit your assignment:

- Access the Application Exercise through Modules on the BIOS 600 Canvas site.

- Upload your PDF.
